url_pochta = "https://www.pochtabank.ru/"
url_pochta_mob = "https://my.pochtabank.ru/"
url_fin = "https://finambank.ru/"
url_urlsb = "https://www.uralsib.ru/"
url_expo = "https://expobank.ru/"
url_vtb = "https://www.vtb.ru/"
url_vtb_mob = "https://vtbmobile.ru/#/"
